### ISSUE TITLE
_ only works with numbers?

### ISSUE THREAD

**Issue by drakeguan** [kachayev/fn.py#72]
``` python
map('%d' % _, range(10))
TypeError: %d format: a number is required, not _Callable
```

**Comment by microamp** [comment]
Not really an answer to your question, but you can do this intead.

``` python
map(str, range(10))
```

**Comment by Digenis** [comment]
It works only for objects whose `__mod__` raises NotImplemented on the right operand
or objects that don't define it at all. In both cases, objects need to have different types.

Perhaps the documentation needs a notice, asking the user to understand
what python calls the [Data model](https://docs.python.org/2/reference/datamodel.html#emulating-numeric-types) in order to avoid such pitfalls

For your question, you can always pass a prepared `'format string, eg {0:d}'.format` to `map()`
